### ISSUE TITLE
Rich text fields munge html in view mode

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/org.civicrm.contactlayout#21]
Here's a can of worms for ya!

Rich text fields - when edited normally save html to the database - here is what a field looks like in view mode when edited via an inbuilt form

![screenshot 2018-09-13 12 51 48](https://user-images.githubusercontent.com/336308/45460802-d516a600-b753-11e8-9cc7-ea992a84e08d.png)

 Edited via the contactlayout block they save escaped html - so it looks like this

![screenshot 2018-09-13 12 50 53](https://user-images.githubusercontent.com/336308/45460771-aac4e880-b753-11e8-9edd-b77af3460cbc.png)

And here is how it renders when viewed on a 'normal' tab
![screenshot 2018-09-13 12 52 54](https://user-images.githubusercontent.com/336308/45460843-f7102880-b753-11e8-8caa-9891ed7bb36a.png)

This is how the field looks in the ContactEditor when it is submitted - ie straight after     $values = $this->exportValues();

```
<p>&lt;p&gt;new stuff&lt;/p&gt;</p>
```

**Comment by nganivet** [comment]
Out of context: we recently gave up on trying to fix this same issue in the word replacement admin screen in core: the 'source' and 'replacement' fields have different behaviors with html inputs, making it impossible to enter a word replacement where either the source or replacement string includes html tags.

So most likely not an easy issue to deal with ...

**Comment by colemanw** [comment]
This appears to be a system-wide problem, possibly caused by the latest round of security fixes. Not just profile forms but core forms are also struggling. Try this:

- Edit a contact's last name to be `I<i>am</i>html`. Obviously html tags are not allowed in a last name field so the correct behavior is for them to be escaped and displayed literally as-is.
- Now view the contact. Note that the last name is *displayed* correctly. It should read "`I<i>am</i>html`".
- But if you click the name to edit, or click "Edit" for the whole contact, it will get garbled. The same problem happens if you stick `last_name` in a profile block.

**Comment by eileenmcnaughton** [comment]
@colemanw FYI - editing the same data in the contact custom field block doesn't garble it - but there is a difference here - ie. I am specifically referring to fields that support html - as defined by their html type & data type. I did wonder if there should be a permission to be able to save html data fields since they are intrinsically insecure

**Comment by colemanw** [comment]
@eileenmcnaughton see https://github.com/civicrm/civicrm-core/pull/12841
